# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from services.auth import auth_pb2 as services_dot_auth_dot_auth__pb2


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/auth.AuthService/Register',
                request_serializer=services_dot_auth_dot_auth__pb2.RegisterRequest.SerializeToString,
                response_deserializer=services_dot_auth_dot_auth__pb2.AuthenticationResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/auth.AuthService/Login',
                request_serializer=services_dot_auth_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=services_dot_auth_dot_auth__pb2.AuthenticationResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/auth.AuthService/Logout',
                request_serializer=services_dot_auth_dot_auth__pb2.LogoutRequest.SerializeToString,
                response_deserializer=services_dot_auth_dot_auth__pb2.LogoutResponse.FromString,
                )
        self.Authenticate = channel.unary_unary(
                '/auth.AuthService/Authenticate',
                request_serializer=services_dot_auth_dot_auth__pb2.AuthenticateRequest.SerializeToString,
                response_deserializer=services_dot_auth_dot_auth__pb2.AuthenticateResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/auth.AuthService/GetUser',
                request_serializer=services_dot_auth_dot_auth__pb2.GetUserRequest.SerializeToString,
                response_deserializer=services_dot_auth_dot_auth__pb2.GetUserResponse.FromString,
                )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Authenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=services_dot_auth_dot_auth__pb2.RegisterRequest.FromString,
                    response_serializer=services_dot_auth_dot_auth__pb2.AuthenticationResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=services_dot_auth_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=services_dot_auth_dot_auth__pb2.AuthenticationResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=services_dot_auth_dot_auth__pb2.LogoutRequest.FromString,
                    response_serializer=services_dot_auth_dot_auth__pb2.LogoutResponse.SerializeToString,
            ),
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=services_dot_auth_dot_auth__pb2.AuthenticateRequest.FromString,
                    response_serializer=services_dot_auth_dot_auth__pb2.AuthenticateResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=services_dot_auth_dot_auth__pb2.GetUserRequest.FromString,
                    response_serializer=services_dot_auth_dot_auth__pb2.GetUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/Register',
            services_dot_auth_dot_auth__pb2.RegisterRequest.SerializeToString,
            services_dot_auth_dot_auth__pb2.AuthenticationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/Login',
            services_dot_auth_dot_auth__pb2.LoginRequest.SerializeToString,
            services_dot_auth_dot_auth__pb2.AuthenticationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/Logout',
            services_dot_auth_dot_auth__pb2.LogoutRequest.SerializeToString,
            services_dot_auth_dot_auth__pb2.LogoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/Authenticate',
            services_dot_auth_dot_auth__pb2.AuthenticateRequest.SerializeToString,
            services_dot_auth_dot_auth__pb2.AuthenticateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/GetUser',
            services_dot_auth_dot_auth__pb2.GetUserRequest.SerializeToString,
            services_dot_auth_dot_auth__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
