# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/shop/shop.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/shop/shop.proto\x12\x04shop\"7\n\nShopStruct\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"/\n\rCreateRequest\x12\x1e\n\x04shop\x18\x01 \x01(\x0b\x32\x10.shop.ShopStruct\"0\n\x0e\x43reateResponse\x12\x1e\n\x04shop\x18\x01 \x01(\x0b\x32\x10.shop.ShopStruct\"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\t\"-\n\x0bGetResponse\x12\x1e\n\x04shop\x18\x01 \x01(\x0b\x32\x10.shop.ShopStruct2r\n\x0bShopService\x12\x35\n\x06\x43reate\x12\x13.shop.CreateRequest\x1a\x14.shop.CreateResponse\"\x00\x12,\n\x03Get\x12\x10.shop.GetRequest\x1a\x11.shop.GetResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.shop.shop_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SHOPSTRUCT']._serialized_start=31
  _globals['_SHOPSTRUCT']._serialized_end=86
  _globals['_CREATEREQUEST']._serialized_start=88
  _globals['_CREATEREQUEST']._serialized_end=135
  _globals['_CREATERESPONSE']._serialized_start=137
  _globals['_CREATERESPONSE']._serialized_end=185
  _globals['_GETREQUEST']._serialized_start=187
  _globals['_GETREQUEST']._serialized_end=211
  _globals['_GETRESPONSE']._serialized_start=213
  _globals['_GETRESPONSE']._serialized_end=258
  _globals['_SHOPSERVICE']._serialized_start=260
  _globals['_SHOPSERVICE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
