// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestForOTPRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestForOTPRequest) Reset()         { *m = RequestForOTPRequest{} }
func (m *RequestForOTPRequest) String() string { return proto.CompactTextString(m) }
func (*RequestForOTPRequest) ProtoMessage()    {}
func (*RequestForOTPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *RequestForOTPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestForOTPRequest.Unmarshal(m, b)
}
func (m *RequestForOTPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestForOTPRequest.Marshal(b, m, deterministic)
}
func (m *RequestForOTPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestForOTPRequest.Merge(m, src)
}
func (m *RequestForOTPRequest) XXX_Size() int {
	return xxx_messageInfo_RequestForOTPRequest.Size(m)
}
func (m *RequestForOTPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestForOTPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestForOTPRequest proto.InternalMessageInfo

func (m *RequestForOTPRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type RequestForOTPResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Ttl                  uint32   `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestForOTPResponse) Reset()         { *m = RequestForOTPResponse{} }
func (m *RequestForOTPResponse) String() string { return proto.CompactTextString(m) }
func (*RequestForOTPResponse) ProtoMessage()    {}
func (*RequestForOTPResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *RequestForOTPResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestForOTPResponse.Unmarshal(m, b)
}
func (m *RequestForOTPResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestForOTPResponse.Marshal(b, m, deterministic)
}
func (m *RequestForOTPResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestForOTPResponse.Merge(m, src)
}
func (m *RequestForOTPResponse) XXX_Size() int {
	return xxx_messageInfo_RequestForOTPResponse.Size(m)
}
func (m *RequestForOTPResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestForOTPResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestForOTPResponse proto.InternalMessageInfo

func (m *RequestForOTPResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RequestForOTPResponse) GetTtl() uint32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type VerifyOTPRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyOTPRequest) Reset()         { *m = VerifyOTPRequest{} }
func (m *VerifyOTPRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyOTPRequest) ProtoMessage()    {}
func (*VerifyOTPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *VerifyOTPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyOTPRequest.Unmarshal(m, b)
}
func (m *VerifyOTPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyOTPRequest.Marshal(b, m, deterministic)
}
func (m *VerifyOTPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyOTPRequest.Merge(m, src)
}
func (m *VerifyOTPRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyOTPRequest.Size(m)
}
func (m *VerifyOTPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyOTPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyOTPRequest proto.InternalMessageInfo

func (m *VerifyOTPRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VerifyOTPRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type VerifyOTPResponse struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyOTPResponse) Reset()         { *m = VerifyOTPResponse{} }
func (m *VerifyOTPResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyOTPResponse) ProtoMessage()    {}
func (*VerifyOTPResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *VerifyOTPResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyOTPResponse.Unmarshal(m, b)
}
func (m *VerifyOTPResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyOTPResponse.Marshal(b, m, deterministic)
}
func (m *VerifyOTPResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyOTPResponse.Merge(m, src)
}
func (m *VerifyOTPResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyOTPResponse.Size(m)
}
func (m *VerifyOTPResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyOTPResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyOTPResponse proto.InternalMessageInfo

func (m *VerifyOTPResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestForOTPRequest)(nil), "auth.RequestForOTPRequest")
	proto.RegisterType((*RequestForOTPResponse)(nil), "auth.RequestForOTPResponse")
	proto.RegisterType((*VerifyOTPRequest)(nil), "auth.VerifyOTPRequest")
	proto.RegisterType((*VerifyOTPResponse)(nil), "auth.VerifyOTPResponse")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x2c, 0xb9, 0x44, 0x82, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xdc, 0xf2, 0x8b, 0xfc, 0x43, 0x02, 0xa0, 0x1c, 0x21, 0x45, 0x2e,
	0x9e, 0x82, 0x8c, 0xfc, 0xbc, 0xd4, 0xf8, 0xbc, 0xd2, 0xdc, 0xa4, 0xd4, 0x22, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x6e, 0xb0, 0x98, 0x1f, 0x58, 0x48, 0xc9, 0x9e, 0x4b, 0x14, 0x4d, 0x6b,
	0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x08, 0x17, 0x6b, 0x49, 0x7e, 0x76, 0x6a, 0x1e, 0x54,
	0x13, 0x84, 0x23, 0x24, 0xc0, 0xc5, 0x5c, 0x52, 0x92, 0x23, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1b,
	0x04, 0x62, 0x2a, 0xd9, 0x70, 0x09, 0x84, 0xa5, 0x16, 0x65, 0xa6, 0x55, 0x22, 0xd9, 0x8b, 0x5d,
	0xaf, 0x10, 0x17, 0x4b, 0x72, 0x7e, 0x4a, 0x2a, 0x58, 0x33, 0x67, 0x10, 0x98, 0xad, 0xa4, 0xca,
	0x25, 0x88, 0xa4, 0x1b, 0x6a, 0xb5, 0x00, 0x17, 0x73, 0x56, 0x79, 0x09, 0x54, 0x33, 0x88, 0x69,
	0x34, 0x93, 0x91, 0x8b, 0xdb, 0xb1, 0xb4, 0x24, 0x23, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55,
	0xc8, 0x8b, 0x8b, 0x17, 0xc5, 0xd5, 0x42, 0x52, 0x7a, 0xe0, 0x40, 0xc1, 0x16, 0x0a, 0x52, 0xd2,
	0x58, 0xe5, 0x20, 0x76, 0x29, 0x31, 0x08, 0xd9, 0x71, 0x71, 0xc2, 0x9d, 0x20, 0x24, 0x06, 0x51,
	0x8b, 0xee, 0x23, 0x29, 0x71, 0x0c, 0x71, 0x98, 0x7e, 0x27, 0xf1, 0x28, 0x51, 0x3d, 0xfd, 0x62,
	0x88, 0xc3, 0x8a, 0xf5, 0x41, 0xca, 0xf4, 0xc1, 0x71, 0x93, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x6e, 0x40, 0xb8, 0x2c, 0xb0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	RequestForOTP(ctx context.Context, in *RequestForOTPRequest, opts ...grpc.CallOption) (*RequestForOTPResponse, error)
	VerifyOTP(ctx context.Context, in *VerifyOTPRequest, opts ...grpc.CallOption) (*VerifyOTPResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) RequestForOTP(ctx context.Context, in *RequestForOTPRequest, opts ...grpc.CallOption) (*RequestForOTPResponse, error) {
	out := new(RequestForOTPResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/RequestForOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyOTP(ctx context.Context, in *VerifyOTPRequest, opts ...grpc.CallOption) (*VerifyOTPResponse, error) {
	out := new(VerifyOTPResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/VerifyOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	RequestForOTP(context.Context, *RequestForOTPRequest) (*RequestForOTPResponse, error)
	VerifyOTP(context.Context, *VerifyOTPRequest) (*VerifyOTPResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) RequestForOTP(ctx context.Context, req *RequestForOTPRequest) (*RequestForOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestForOTP not implemented")
}
func (*UnimplementedAuthServiceServer) VerifyOTP(ctx context.Context, req *VerifyOTPRequest) (*VerifyOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyOTP not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_RequestForOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestForOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RequestForOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/RequestForOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RequestForOTP(ctx, req.(*RequestForOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/VerifyOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyOTP(ctx, req.(*VerifyOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestForOTP",
			Handler:    _AuthService_RequestForOTP_Handler,
		},
		{
			MethodName: "VerifyOTP",
			Handler:    _AuthService_VerifyOTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
