// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shop.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Shop struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt            string   `protobuf:"bytes,6,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shop) Reset()         { *m = Shop{} }
func (m *Shop) String() string { return proto.CompactTextString(m) }
func (*Shop) ProtoMessage()    {}
func (*Shop) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{0}
}

func (m *Shop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shop.Unmarshal(m, b)
}
func (m *Shop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shop.Marshal(b, m, deterministic)
}
func (m *Shop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shop.Merge(m, src)
}
func (m *Shop) XXX_Size() int {
	return xxx_messageInfo_Shop.Size(m)
}
func (m *Shop) XXX_DiscardUnknown() {
	xxx_messageInfo_Shop.DiscardUnknown(m)
}

var xxx_messageInfo_Shop proto.InternalMessageInfo

func (m *Shop) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Shop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Shop) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Shop) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Shop) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Shop) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type FetchShopRequest struct {
	ShopID               string   `protobuf:"bytes,1,opt,name=shopID,proto3" json:"shopID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchShopRequest) Reset()         { *m = FetchShopRequest{} }
func (m *FetchShopRequest) String() string { return proto.CompactTextString(m) }
func (*FetchShopRequest) ProtoMessage()    {}
func (*FetchShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{1}
}

func (m *FetchShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchShopRequest.Unmarshal(m, b)
}
func (m *FetchShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchShopRequest.Marshal(b, m, deterministic)
}
func (m *FetchShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchShopRequest.Merge(m, src)
}
func (m *FetchShopRequest) XXX_Size() int {
	return xxx_messageInfo_FetchShopRequest.Size(m)
}
func (m *FetchShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchShopRequest proto.InternalMessageInfo

func (m *FetchShopRequest) GetShopID() string {
	if m != nil {
		return m.ShopID
	}
	return ""
}

type FetchShopResponse struct {
	Shop                 *Shop    `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchShopResponse) Reset()         { *m = FetchShopResponse{} }
func (m *FetchShopResponse) String() string { return proto.CompactTextString(m) }
func (*FetchShopResponse) ProtoMessage()    {}
func (*FetchShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{2}
}

func (m *FetchShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchShopResponse.Unmarshal(m, b)
}
func (m *FetchShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchShopResponse.Marshal(b, m, deterministic)
}
func (m *FetchShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchShopResponse.Merge(m, src)
}
func (m *FetchShopResponse) XXX_Size() int {
	return xxx_messageInfo_FetchShopResponse.Size(m)
}
func (m *FetchShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchShopResponse proto.InternalMessageInfo

func (m *FetchShopResponse) GetShop() *Shop {
	if m != nil {
		return m.Shop
	}
	return nil
}

type FetchShopsByUserIDRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchShopsByUserIDRequest) Reset()         { *m = FetchShopsByUserIDRequest{} }
func (m *FetchShopsByUserIDRequest) String() string { return proto.CompactTextString(m) }
func (*FetchShopsByUserIDRequest) ProtoMessage()    {}
func (*FetchShopsByUserIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{3}
}

func (m *FetchShopsByUserIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchShopsByUserIDRequest.Unmarshal(m, b)
}
func (m *FetchShopsByUserIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchShopsByUserIDRequest.Marshal(b, m, deterministic)
}
func (m *FetchShopsByUserIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchShopsByUserIDRequest.Merge(m, src)
}
func (m *FetchShopsByUserIDRequest) XXX_Size() int {
	return xxx_messageInfo_FetchShopsByUserIDRequest.Size(m)
}
func (m *FetchShopsByUserIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchShopsByUserIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchShopsByUserIDRequest proto.InternalMessageInfo

func (m *FetchShopsByUserIDRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type FetchShopByUserIDResponse struct {
	ShopName             []string `protobuf:"bytes,1,rep,name=shopName,proto3" json:"shopName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchShopByUserIDResponse) Reset()         { *m = FetchShopByUserIDResponse{} }
func (m *FetchShopByUserIDResponse) String() string { return proto.CompactTextString(m) }
func (*FetchShopByUserIDResponse) ProtoMessage()    {}
func (*FetchShopByUserIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{4}
}

func (m *FetchShopByUserIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchShopByUserIDResponse.Unmarshal(m, b)
}
func (m *FetchShopByUserIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchShopByUserIDResponse.Marshal(b, m, deterministic)
}
func (m *FetchShopByUserIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchShopByUserIDResponse.Merge(m, src)
}
func (m *FetchShopByUserIDResponse) XXX_Size() int {
	return xxx_messageInfo_FetchShopByUserIDResponse.Size(m)
}
func (m *FetchShopByUserIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchShopByUserIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchShopByUserIDResponse proto.InternalMessageInfo

func (m *FetchShopByUserIDResponse) GetShopName() []string {
	if m != nil {
		return m.ShopName
	}
	return nil
}

func init() {
	proto.RegisterType((*Shop)(nil), "shop.Shop")
	proto.RegisterType((*FetchShopRequest)(nil), "shop.FetchShopRequest")
	proto.RegisterType((*FetchShopResponse)(nil), "shop.FetchShopResponse")
	proto.RegisterType((*FetchShopsByUserIDRequest)(nil), "shop.FetchShopsByUserIDRequest")
	proto.RegisterType((*FetchShopByUserIDResponse)(nil), "shop.FetchShopByUserIDResponse")
}

func init() {
	proto.RegisterFile("shop.proto", fileDescriptor_0f3030369b20fd61)
}

var fileDescriptor_0f3030369b20fd61 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xbb, 0x6d, 0xfe, 0xe1, 0x9f, 0x29, 0x88, 0x0e, 0x58, 0x63, 0x10, 0x2d, 0x7b, 0x2a,
	0x1e, 0x12, 0x68, 0x0e, 0x9e, 0x3c, 0x58, 0x8a, 0xd0, 0x8b, 0x87, 0x14, 0x11, 0xbc, 0xd5, 0x64,
	0x20, 0x01, 0x6d, 0x62, 0x36, 0x11, 0xfc, 0x2e, 0x5e, 0xfd, 0x9e, 0xb2, 0xb3, 0x6b, 0x1a, 0x02,
	0x9e, 0xb2, 0xfb, 0xde, 0x9b, 0xdd, 0xf7, 0x5b, 0x02, 0xa0, 0xf2, 0xb2, 0x0a, 0xab, 0xba, 0x6c,
	0x4a, 0x74, 0xf4, 0x5a, 0x7e, 0x09, 0x70, 0xb6, 0x79, 0x59, 0xe1, 0x11, 0x8c, 0x8b, 0xcc, 0x17,
	0x73, 0xb1, 0xf0, 0x92, 0x71, 0x91, 0x21, 0x82, 0xb3, 0xdf, 0xbd, 0x91, 0x3f, 0x66, 0x85, 0xd7,
	0x38, 0x03, 0xb7, 0x55, 0x54, 0x6f, 0xd6, 0xfe, 0x84, 0x55, 0xbb, 0xc3, 0x0b, 0xf0, 0xd2, 0x9a,
	0x76, 0x0d, 0x65, 0x77, 0x8d, 0xef, 0xb0, 0x75, 0x10, 0xb4, 0xdb, 0x56, 0x99, 0x75, 0xff, 0x19,
	0xb7, 0x13, 0xb4, 0x9b, 0xd1, 0x2b, 0x19, 0xd7, 0x35, 0x6e, 0x27, 0xc8, 0x6b, 0x38, 0xbe, 0xa7,
	0x26, 0xcd, 0x75, 0xc5, 0x84, 0xde, 0x5b, 0x52, 0x8d, 0x6e, 0xa1, 0xab, 0x6f, 0xd6, 0xb6, 0xad,
	0xdd, 0xc9, 0x18, 0x4e, 0x7a, 0x59, 0x55, 0x95, 0x7b, 0x45, 0x78, 0x09, 0xcc, 0xc9, 0xd1, 0xe9,
	0x12, 0x42, 0x7e, 0x00, 0x4e, 0x18, 0xfe, 0x18, 0xce, 0xbb, 0x21, 0xb5, 0xfa, 0x7c, 0x64, 0xa0,
	0xde, 0x4d, 0x96, 0x57, 0xf4, 0x79, 0xe5, 0x4d, 0x6f, 0xe8, 0x30, 0x63, 0x6f, 0x0c, 0xe0, 0xbf,
	0x3e, 0xf9, 0x41, 0x3f, 0x9e, 0x98, 0x4f, 0x16, 0x5e, 0xd2, 0xed, 0x97, 0xdf, 0x02, 0xa6, 0x7a,
	0x68, 0x4b, 0xf5, 0x47, 0x91, 0x12, 0xde, 0x82, 0xd7, 0x1d, 0x84, 0x33, 0x53, 0x6e, 0xc8, 0x1b,
	0xfc, 0xa1, 0xcb, 0x11, 0x3e, 0xf5, 0x88, 0x7f, 0x7b, 0xe0, 0xd5, 0x20, 0x3e, 0xa4, 0x0a, 0x86,
	0x81, 0x21, 0x81, 0x1c, 0xad, 0xce, 0x9e, 0x4f, 0xc3, 0x48, 0x99, 0x92, 0x2a, 0xd2, 0xf1, 0x88,
	0x7f, 0x9a, 0x17, 0x97, 0x3f, 0xf1, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0xfe, 0xb7, 0x70,
	0x49, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShopServiceClient is the client API for ShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShopServiceClient interface {
	FetchShop(ctx context.Context, in *FetchShopRequest, opts ...grpc.CallOption) (*FetchShopRequest, error)
	FetchShopByUserID(ctx context.Context, in *FetchShopsByUserIDRequest, opts ...grpc.CallOption) (*FetchShopByUserIDResponse, error)
}

type shopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopServiceClient(cc grpc.ClientConnInterface) ShopServiceClient {
	return &shopServiceClient{cc}
}

func (c *shopServiceClient) FetchShop(ctx context.Context, in *FetchShopRequest, opts ...grpc.CallOption) (*FetchShopRequest, error) {
	out := new(FetchShopRequest)
	err := c.cc.Invoke(ctx, "/shop.ShopService/FetchShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) FetchShopByUserID(ctx context.Context, in *FetchShopsByUserIDRequest, opts ...grpc.CallOption) (*FetchShopByUserIDResponse, error) {
	out := new(FetchShopByUserIDResponse)
	err := c.cc.Invoke(ctx, "/shop.ShopService/FetchShopByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServiceServer is the server API for ShopService service.
type ShopServiceServer interface {
	FetchShop(context.Context, *FetchShopRequest) (*FetchShopRequest, error)
	FetchShopByUserID(context.Context, *FetchShopsByUserIDRequest) (*FetchShopByUserIDResponse, error)
}

// UnimplementedShopServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShopServiceServer struct {
}

func (*UnimplementedShopServiceServer) FetchShop(ctx context.Context, req *FetchShopRequest) (*FetchShopRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchShop not implemented")
}
func (*UnimplementedShopServiceServer) FetchShopByUserID(ctx context.Context, req *FetchShopsByUserIDRequest) (*FetchShopByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchShopByUserID not implemented")
}

func RegisterShopServiceServer(s *grpc.Server, srv ShopServiceServer) {
	s.RegisterService(&_ShopService_serviceDesc, srv)
}

func _ShopService_FetchShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).FetchShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop.ShopService/FetchShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).FetchShop(ctx, req.(*FetchShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_FetchShopByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchShopsByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).FetchShopByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop.ShopService/FetchShopByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).FetchShopByUserID(ctx, req.(*FetchShopsByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shop.ShopService",
	HandlerType: (*ShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchShop",
			Handler:    _ShopService_FetchShop_Handler,
		},
		{
			MethodName: "FetchShopByUserID",
			Handler:    _ShopService_FetchShopByUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop.proto",
}
