// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/shop/shop.proto

package shop

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShopStruct struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopStruct) Reset()         { *m = ShopStruct{} }
func (m *ShopStruct) String() string { return proto.CompactTextString(m) }
func (*ShopStruct) ProtoMessage()    {}
func (*ShopStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_846ffd47eaa9ea2a, []int{0}
}

func (m *ShopStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopStruct.Unmarshal(m, b)
}
func (m *ShopStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopStruct.Marshal(b, m, deterministic)
}
func (m *ShopStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopStruct.Merge(m, src)
}
func (m *ShopStruct) XXX_Size() int {
	return xxx_messageInfo_ShopStruct.Size(m)
}
func (m *ShopStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopStruct.DiscardUnknown(m)
}

var xxx_messageInfo_ShopStruct proto.InternalMessageInfo

func (m *ShopStruct) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ShopStruct) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ShopStruct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateRequest struct {
	Shop                 *ShopStruct `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_846ffd47eaa9ea2a, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetShop() *ShopStruct {
	if m != nil {
		return m.Shop
	}
	return nil
}

type CreateResponse struct {
	Shop                 *ShopStruct `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_846ffd47eaa9ea2a, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetShop() *ShopStruct {
	if m != nil {
		return m.Shop
	}
	return nil
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_846ffd47eaa9ea2a, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Shop                 *ShopStruct `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_846ffd47eaa9ea2a, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetShop() *ShopStruct {
	if m != nil {
		return m.Shop
	}
	return nil
}

type GetByUserIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByUserIDRequest) Reset()         { *m = GetByUserIDRequest{} }
func (m *GetByUserIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetByUserIDRequest) ProtoMessage()    {}
func (*GetByUserIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_846ffd47eaa9ea2a, []int{5}
}

func (m *GetByUserIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUserIDRequest.Unmarshal(m, b)
}
func (m *GetByUserIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUserIDRequest.Marshal(b, m, deterministic)
}
func (m *GetByUserIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUserIDRequest.Merge(m, src)
}
func (m *GetByUserIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetByUserIDRequest.Size(m)
}
func (m *GetByUserIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUserIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUserIDRequest proto.InternalMessageInfo

func (m *GetByUserIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetByUserIDResponse struct {
	Shop                 []*ShopStruct `protobuf:"bytes,1,rep,name=shop,proto3" json:"shop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetByUserIDResponse) Reset()         { *m = GetByUserIDResponse{} }
func (m *GetByUserIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetByUserIDResponse) ProtoMessage()    {}
func (*GetByUserIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_846ffd47eaa9ea2a, []int{6}
}

func (m *GetByUserIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUserIDResponse.Unmarshal(m, b)
}
func (m *GetByUserIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUserIDResponse.Marshal(b, m, deterministic)
}
func (m *GetByUserIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUserIDResponse.Merge(m, src)
}
func (m *GetByUserIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetByUserIDResponse.Size(m)
}
func (m *GetByUserIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUserIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUserIDResponse proto.InternalMessageInfo

func (m *GetByUserIDResponse) GetShop() []*ShopStruct {
	if m != nil {
		return m.Shop
	}
	return nil
}

func init() {
	proto.RegisterType((*ShopStruct)(nil), "shop.ShopStruct")
	proto.RegisterType((*CreateRequest)(nil), "shop.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "shop.CreateResponse")
	proto.RegisterType((*GetRequest)(nil), "shop.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "shop.GetResponse")
	proto.RegisterType((*GetByUserIDRequest)(nil), "shop.GetByUserIDRequest")
	proto.RegisterType((*GetByUserIDResponse)(nil), "shop.GetByUserIDResponse")
}

func init() {
	proto.RegisterFile("proto/shop/shop.proto", fileDescriptor_846ffd47eaa9ea2a)
}

var fileDescriptor_846ffd47eaa9ea2a = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0x52, 0x22, 0xbe, 0x60, 0xd1, 0xa9, 0x62, 0x0c, 0x1e, 0x24, 0xf4, 0xe0, 0x41,
	0x2a, 0xb4, 0xd4, 0x8b, 0x37, 0x2d, 0x84, 0x5e, 0x53, 0x3c, 0x4b, 0x6d, 0x06, 0x9a, 0x83, 0xdd,
	0xb8, 0xbb, 0x11, 0xfc, 0x67, 0xfe, 0x3c, 0xc9, 0xc4, 0xb4, 0xa6, 0x5a, 0xd0, 0x4b, 0xd8, 0x79,
	0x33, 0xf3, 0xbe, 0x99, 0x21, 0x38, 0x2d, 0xb4, 0xb2, 0xea, 0xc6, 0x2c, 0x55, 0x21, 0x9f, 0x81,
	0xc4, 0xd4, 0xa9, 0xde, 0xf1, 0x14, 0x98, 0x2d, 0x55, 0x31, 0xb3, 0xba, 0x5c, 0x58, 0xea, 0xc2,
	0xcd, 0xb3, 0xd0, 0xb9, 0x74, 0xae, 0x0e, 0x52, 0x37, 0xcf, 0xe8, 0x0c, 0xfb, 0xa5, 0x61, 0xfd,
	0x94, 0x67, 0xa1, 0x2b, 0xa2, 0x5f, 0x85, 0xd3, 0x8c, 0x08, 0x9d, 0xd5, 0xfc, 0x85, 0x43, 0x4f,
	0x54, 0x79, 0xc7, 0x63, 0x1c, 0x3e, 0x68, 0x9e, 0x5b, 0x4e, 0xf9, 0xb5, 0x64, 0x63, 0xa9, 0x0f,
	0x61, 0x88, 0x5f, 0x30, 0x3c, 0x1a, 0x08, 0x7c, 0x43, 0x4b, 0xeb, 0x09, 0x6e, 0xd1, 0x6d, 0xda,
	0x4c, 0xa1, 0x56, 0x86, 0xff, 0xd8, 0x77, 0x01, 0x24, 0x6c, 0x1b, 0xd6, 0xd6, 0xe4, 0xf1, 0x08,
	0x81, 0x64, 0xff, 0x65, 0xd9, 0x07, 0x25, 0x6c, 0xef, 0xdf, 0x1f, 0xab, 0x25, 0x27, 0xbb, 0xac,
	0xef, 0xd0, 0x6b, 0x55, 0xfd, 0x40, 0x78, 0xbb, 0x11, 0xc3, 0x0f, 0x07, 0x81, 0x88, 0xac, 0xdf,
	0xf2, 0x05, 0xd3, 0x18, 0x7e, 0xbd, 0x3d, 0xf5, 0xea, 0x8e, 0xd6, 0x09, 0xa3, 0x93, 0xb6, 0x58,
	0xa3, 0xe2, 0x3d, 0xba, 0x86, 0x97, 0xb0, 0xa5, 0x2f, 0xca, 0xe6, 0x0e, 0xd1, 0xf1, 0x37, 0x65,
	0x5d, 0x3d, 0x91, 0x63, 0x34, 0x13, 0x53, 0xb8, 0xae, 0xd9, 0x5a, 0x35, 0x3a, 0xff, 0x25, 0xd3,
	0xb8, 0x3c, 0xfb, 0xf2, 0xdf, 0x8c, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x92, 0x35, 0x87, 0x66,
	0x50, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShopServiceClient is the client API for ShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShopServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetByUserID(ctx context.Context, in *GetByUserIDRequest, opts ...grpc.CallOption) (*GetByUserIDResponse, error)
}

type shopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopServiceClient(cc grpc.ClientConnInterface) ShopServiceClient {
	return &shopServiceClient{cc}
}

func (c *shopServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/shop.ShopService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/shop.ShopService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetByUserID(ctx context.Context, in *GetByUserIDRequest, opts ...grpc.CallOption) (*GetByUserIDResponse, error) {
	out := new(GetByUserIDResponse)
	err := c.cc.Invoke(ctx, "/shop.ShopService/GetByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServiceServer is the server API for ShopService service.
type ShopServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetByUserID(context.Context, *GetByUserIDRequest) (*GetByUserIDResponse, error)
}

// UnimplementedShopServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShopServiceServer struct {
}

func (*UnimplementedShopServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedShopServiceServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedShopServiceServer) GetByUserID(ctx context.Context, req *GetByUserIDRequest) (*GetByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUserID not implemented")
}

func RegisterShopServiceServer(s *grpc.Server, srv ShopServiceServer) {
	s.RegisterService(&_ShopService_serviceDesc, srv)
}

func _ShopService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop.ShopService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop.ShopService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop.ShopService/GetByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetByUserID(ctx, req.(*GetByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shop.ShopService",
	HandlerType: (*ShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ShopService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ShopService_Get_Handler,
		},
		{
			MethodName: "GetByUserID",
			Handler:    _ShopService_GetByUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shop/shop.proto",
}
